--vous vous mettez dans la base de donné par defaut de posgres

DROP TABLE IF EXISTS PROFESSOR_LESSON;
DROP TABLE IF EXISTS PRESENCE_RECORD;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS SECRETARY;
DROP TABLE IF EXISTS LESSON;
DROP TABLE IF EXISTS PROFESSOR;

CREATE TABLE STUDENT
(
	STUDENT_ID VARCHAR(255) PRIMARY KEY,
	PASSWORD VARCHAR(255) NOT NULL,
	NAME VARCHAR(255),
	FIRST_NAME VARCHAR(255),
	CLASS VARCHAR(255)
);

CREATE TABLE SECRETARY
(
	SECRET_ID VARCHAR(255) PRIMARY KEY,
	PASSWORD VARCHAR(255) NOT NULL,
	NAME VARCHAR(255),
	FIRST_NAME VARCHAR(255)
);

CREATE TABLE PROFESSOR
(
	PROF_ID VARCHAR(255) PRIMARY KEY,
	PASSWORD VARCHAR(255) NOT NULL,
	NAME VARCHAR(255),
	FIRST_NAME VARCHAR(255)
);

CREATE TABLE LESSON
(
	LESSON_ID VARCHAR(255) PRIMARY KEY,
	DATE DATE,
	DURATION INTEGER NOT NULL,
	NAME VARCHAR(255)
);

CREATE TABLE PRESENCE_RECORD
(
	LESSON_ID VARCHAR(255) REFERENCES LESSON(LESSON_ID),
	PRESENCE BOOLEAN,
	STUDENT_ID VARCHAR(255) REFERENCES STUDENT(STUDENT_ID),
	PRIMARY KEY (LESSON_ID, STUDENT_ID)	
);

CREATE TABLE PROFESSOR_LESSON
(
	PROF_ID VARCHAR(255),
 	FOREIGN KEY (PROF_ID) REFERENCES PROFESSOR (PROF_ID),
	LESSON_ID VARCHAR(255),
 	FOREIGN KEY (LESSON_ID ) REFERENCES LESSON (LESSON_ID),
	PRIMARY KEY (PROF_ID, LESSON_ID)
);
